import type { MenuItem } from "./types";

export const MENU: readonly MenuItem[] = [
  {
    id: "espresso",
    name: "Espresso",
    description: "A short, strong shot of our house blend.",
    price: 200,
    category: "drink",
    inStock: true,
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    description: "Espresso with steamed milk and a thick foam cap.",
    price: 320,
    category: "drink",
    inStock: true,
  },
  {
    id: "latte",
    name: "Caffè Latte",
    description: "Espresso topped up with silky steamed milk.",
    price: 350,
    category: "drink",
    inStock: true,
  },
  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    description: "Rich cocoa with steamed milk.",
    price: 300,
    category: "drink",
    inStock: true,
  },
  {
    id: "iced-tea",
    name: "Iced Peach Tea",
    description: "Black tea brewed cold with a hint of peach.",
    price: 280,
    category: "drink",
    inStock: false,
  },
  {
    id: "croissant",
    name: "Butter Croissant",
    description: "Flaky, baked fresh every morning.",
    price: 250,
    category: "food",
    inStock: true,
  },
  {
    id: "muffin",
    name: "Blueberry Muffin",
    description: "Soft muffin packed with blueberries.",
    price: 290,
    category: "food",
    inStock: true,
  },
  {
    id: "toastie",
    name: "Ham & Cheese Toastie",
    description: "Grilled sourdough with ham and melted cheddar.",
    price: 480,
    category: "food",
    inStock: true,
  },
  {
    id: "avocado-toast",
    name: "Avocado Toast",
    description: "Smashed avocado, lemon and chilli on rye.",
    price: 550,
    category: "food",
    inStock: false,
  },
];
